name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: Platane/snk@v3
        with:
          github_user_name: yan-bin2009
          outputs: |
            github-snake.svg
            github-snake-dark.svg?palette=github-dark

      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add github-snake.svg github-snake-dark.svg
          git commit -m "Update snake" || exit 0
          git push
